language: c
os: linux

install:
  - wget https://raw.githubusercontent.com/${TRAVIS_REPO_SLUG}/master/tools/check-signed-off.sh
  - chmod u+x check-signed-off.sh
script: ./check-signed-off.sh --travis

branches:
  only:
  - master
  - gh-pages
  - /.*/
