version: "{build}"
branches:
  except:
  - coverity_scan
  - gh_pages
skip_tags: true

# Build matrix setup.
image:
  - Visual Studio 2017
platform:
  - Win32
  - x64
environment:
  matrix:
    - JOB_NAME: Build Tests
      OPTS: --buildoption-test
    - JOB_NAME: Unit Tests
      OPTS: --unittests
    - JOB_NAME: Jerry Tests
      OPTS: --jerry-tests
    - JOB_NAME: Jerry Test-suite
      OPTS: --jerry-test-suite
    - JOB_NAME: Kangax Tests
      OPTS: --kangax-tests
    - JOB_NAME: Conformance Tests
      OPTS: --test262

# Steps of a job.
build_script:
  - if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR="Visual Studio 15 2017"
  - if "%PLATFORM%"=="x64" set CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
  - python tools\run-tests.py --buildoptions=--cmake-param=-G%CMAKE_GENERATOR% %OPTS%
